service: backlog-per-instance-calculator

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  profile: dev
  environment:
    QUEUE_URL: "https://sqs.eu-west-1.amazonaws.com/399971917915/my_queue"
    ASG_NAME: "sqs_workers_autoscaling_group"

functions:
  calculateBacklogPerInstance:
    handler: calculateBacklogPerInstance.handler
    name: backlog-per-instance-calculator

    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-bundle

custom:
  bundle:
      linting: false
