service: backlog-per-instance-calculator

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  variablesResolutionMode: 20210326
  region: eu-west-1
  profile: dev
  environment:
    QUEUE_URL: ${ssm:/sqsAutoscaling/queueUrl}
    ASG_NAME: ${ssm:/sqsAutoscaling/autoScalingGroupName}
  iamRoleStatements:
    - ${file(iam/QueueIAM.yml):MyQueueIAM}
    - ${file(iam/AutoScaleIAM.yml):AutoScaleIAM}
    - ${file(iam/CloudWatchIAM.yml):CloudWatchIAM}

functions:
  calculateBacklogPerInstance:
    handler: src/handlers/calculateBacklogPerInstance.handler
    name: backlog-per-instance-calculator
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-bundle

custom:
  bundle:
    linting: false
