service: backlog-per-instance-calculator

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  cfLogs: true
  eventBridge:
    useCloudFormation: true
  lambdaHashingVersion: 20201221
  variablesResolutionMode: 20210326
  memorySize: 128
  timeout: 3
  region: eu-west-1
  profile: dev
  iamRoleStatements:
    - ${file(iam/QueueIAM.yml):MyQueueIAM}
    - ${file(iam/AutoScaleIAM.yml):AutoScaleIAM}
    - ${file(iam/CloudWatchIAM.yml):CloudWatchIAM}
  environment:
    QUEUE_URL: ${ssm:/sqsAutoscaling/queueUrl}
    ASG_NAME: ${ssm:/sqsAutoscaling/autoScalingGroupName}

functions:
  calculateBacklogPerInstance:
    handler: src/handlers/calculateBacklogPerInstance.handler
    name: backlog-per-instance-calculator
    events:
      - schedule: rate(1 minute)
  logAutoScalingGroupEvents:
    handler: src/handlers/logAutoScalingGroupEvents.handler
    name: log-auto-scaling-group-events
    events:
      - eventBridge:
          enabled: true
          pattern:
            source:
              - aws.autoscaling
            detail-type:
              - 'EC2 Instance Launch Successful'
              - 'EC2 Instance Launch Unsuccessful'
              - 'EC2 Instance Terminate Successful'
              - 'EC2 Instance Terminate Unsuccessful'
            detail:
              AutoScalingGroupName:
                - ${ssm:/sqsAutoscaling/autoScalingGroupName}

resources:
  Resources:
    CalculateBacklogPerInstanceLogGroup:
      Properties:
        RetentionInDays: "30"
    LogAutoScalingGroupEventsLogGroup:
      Properties:
        RetentionInDays: "30"

plugins:
  - serverless-bundle
custom:
  bundle:
    linting: false